package es.ulpgc.ratingames.model;

public enum Genre {
    SHOOTERS, ADVENTURE,ACTION,PlATFORMER, HORROR, SURVIVAL,
    SPORTS, STRATEGY, MOBA, SIMULATION, PUZZLERS, PARTYGAMES,
    RPG, RACING, FIGHTING
}
